name: AICup
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.23
  - pandas>=1.5
  - scipy
  - matplotlib
  - scikit-learn>=1.2
  - jupyterlab
  - pytorch
  - pytorch-cuda=11.8
  - torchmetrics